### ISSUE TITLE
Make pygame camera movable during playback of recorded states.

### ISSUE THREAD

**Issue by ll7** [ll7/robot_sf_ll7#33]
What needs to be improved is that during playback it is not possible to move the camera.

_Originally posted by @ll7 in https://github.com/ll7/robot_sf_ll7/issues/32#issuecomment-2146992622_

**Comment by ll7** [comment]
Test this by using `test_pygame/test_load_and_visualize_states.py` and try to move the camera with arrow keys and plus minus.

**Comment by JuliusMiller** [comment]
https://github.com/ll7/robot_sf_ll7/blob/59d9296223f50e4f023d7ee1063b826c890ce331/robot_sf/render/playback_recording.py#L41C1-L41C45

was missing

**Comment by ll7** [comment]
Thank you! I will close this issue, because you fixed it in #42
